# Generated by Django 3.1.5 on 2021-01-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='buttonlink',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
