# Generated by Django 3.1.5 on 2021-01-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210124_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
